#!/usr/bin/env python3
"""
FBA-Bench GUI Launcher
Professional, one-click application launcher that handles all setup automatically.
"""

import logging
import signal
import subprocess
import sys
import threading
import time
import webbrowser
from pathlib import Path
from typing import Any, Dict

# Configure logging for launcher
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


class FBABenchGUILauncher:
    """Professional GUI launcher for FBA-Bench platform."""

    def __init__(self):
        self.project_root = Path(__file__).parent.absolute()
        self.frontend_dir = self.project_root / "frontend"
        self.env_file = self.project_root / ".env"
        self.processes: Dict[str, subprocess.Popen] = {}
        self.running = True

    def check_requirements(self) -> Dict[str, bool]:
        """Check if all required tools are available."""
        requirements = {}

        # Check Python version
        requirements["python"] = sys.version_info >= (3, 9)

        # Check Poetry
        try:
            subprocess.run(["poetry", "--version"], capture_output=True, check=True)
            requirements["poetry"] = True
        except (subprocess.CalledProcessError, FileNotFoundError):
            requirements["poetry"] = False

        # Check Node.js
        try:
            subprocess.run(["node", "--version"], capture_output=True, check=True)
            requirements["node"] = True
        except (subprocess.CalledProcessError, FileNotFoundError):
            requirements["node"] = False

        # Check npm (try multiple methods on Windows)
        try:
            # Try npm directly first
            result = subprocess.run(
                ["npm", "--version"], capture_output=True, check=True, shell=True
            )
            requirements["npm"] = True
        except (subprocess.CalledProcessError, FileNotFoundError):
            try:
                # Try with full path (Windows common location)
                result = subprocess.run(["npm.cmd", "--version"], capture_output=True, check=True)
                requirements["npm"] = True
            except (subprocess.CalledProcessError, FileNotFoundError):
                # If Node.js works, npm should be available
                requirements["npm"] = requirements.get("node", False)

        return requirements

    def check_env_configuration(self) -> Dict[str, Any]:
        """Check .env file status and required configurations."""
        if not self.env_file.exists():
            return {"exists": False, "valid": False, "missing_keys": []}

        # Read existing .env file
        env_content = {}
        try:
            with open(self.env_file) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, value = line.split("=", 1)
                        env_content[key.strip()] = value.strip()
        except Exception as e:
            logger.error(f"Failed to read .env file: {e}")
            return {"exists": True, "valid": False, "error": str(e)}

        # Check for required keys
        required_keys = [
            "ENVIRONMENT",
            "AUTH_ENABLED",
            "FBA_CORS_ALLOW_ORIGINS",
            "MONGO_INITDB_ROOT_USERNAME",
            "MONGO_INITDB_ROOT_PASSWORD",
            "REDIS_PASSWORD",
            "FBA_BENCH_REDIS_URL",
        ]

        missing_keys = [
            key for key in required_keys if key not in env_content or not env_content[key]
        ]

        return {
            "exists": True,
            "valid": len(missing_keys) == 0,
            "missing_keys": missing_keys,
            "content": env_content,
        }

    def create_default_env(self) -> bool:
        """Create a default .env file with development settings."""
        try:
            default_content = """# FBA-Bench Configuration - Auto-Generated for Development
# Generated by FBA-Bench GUI Launcher

# === DEVELOPMENT CONFIGURATION ===
ENVIRONMENT=development
AUTH_ENABLED=false
AUTH_TEST_BYPASS=true
AUTH_PROTECT_DOCS=false
FBA_CORS_ALLOW_ORIGINS=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000

# === DATABASE CONFIGURATION ===
MONGO_INITDB_ROOT_USERNAME=clearml
MONGO_INITDB_ROOT_PASSWORD=dev_password_123
REDIS_PASSWORD=dev_redis_123
FBA_BENCH_REDIS_URL=redis://:dev_redis_123@localhost:6379/0

# === API CONFIGURATION ===
API_RATE_LIMIT=1000/minute

# === CLEARML CONFIGURATION (Optional) ===
# Uncomment and configure if using ClearML:
# CLEARML_API_ACCESS_KEY=your_access_key
# CLEARML_API_SECRET_KEY=your_secret_key
"""

            with open(self.env_file, "w") as f:
                f.write(default_content)

            logger.info(f"Created default .env file at {self.env_file}")
            return True

        except Exception as e:
            logger.error(f"Failed to create .env file: {e}")
            return False

    def start_backend(self) -> bool:
        """Start the FastAPI backend server."""
        try:
            logger.info("Starting FBA-Bench API server...")

            # Install dependencies if needed
            install_cmd = ["poetry", "install"]
            subprocess.run(install_cmd, cwd=self.project_root, check=True)

            # Start the API server
            api_cmd = [
                "poetry",
                "run",
                "uvicorn",
                "fba_bench_api.main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
                "--reload",
            ]

            self.processes["backend"] = subprocess.Popen(
                api_cmd,
                cwd=self.project_root,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )

            # Wait for backend to start
            time.sleep(5)

            if self.processes["backend"].poll() is None:
                logger.info("✓ Backend API server started successfully on http://localhost:8000")
                return True
            else:
                logger.error("✗ Backend server failed to start")
                return False

        except Exception as e:
            logger.error(f"Failed to start backend: {e}")
            return False

    def start_frontend(self) -> bool:
        """Start the React frontend development server."""
        try:
            logger.info("Starting FBA-Bench frontend...")

            # Check if node_modules exists, install if not
            node_modules = self.frontend_dir / "node_modules"
            if not node_modules.exists():
                logger.info("Installing frontend dependencies...")
                npm_install = subprocess.run(
                    "npm install", cwd=self.frontend_dir, capture_output=True, text=True, shell=True
                )
                if npm_install.returncode != 0:
                    logger.error(f"npm install failed: {npm_install.stderr}")
                    return False

            # Start the development server
            self.processes["frontend"] = subprocess.Popen(
                "npm run dev",
                cwd=self.frontend_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                shell=True,
            )

            # Wait for frontend to start
            time.sleep(8)

            if self.processes["frontend"].poll() is None:
                logger.info("✓ Frontend development server started successfully")
                return True
            else:
                logger.error("✗ Frontend server failed to start")
                return False

        except Exception as e:
            logger.error(f"Failed to start frontend: {e}")
            return False

    def open_browser(self) -> None:
        """Open the web browser to the application."""
        try:
            # Wait a moment for servers to be fully ready
            time.sleep(5)

            # Try different possible URLs (including auto-detected port)
            urls = [
                "http://localhost:5173",  # Vite default
                "http://localhost:3000",  # Common alternative
                "http://localhost:3001",  # If 3000 is busy
                "http://127.0.0.1:5173",
                "http://127.0.0.1:3000",
                "http://127.0.0.1:3001",
            ]

            for url in urls:
                try:
                    import requests

                    response = requests.get(url, timeout=3)
                    if response.status_code in [200, 404]:  # 404 is okay for SPA
                        logger.info(f"✓ Opening FBA-Bench GUI at {url}")
                        webbrowser.open(url)
                        return
                except:
                    continue

            # Fallback - open first URL anyway
            logger.info("Opening browser at default URL...")
            webbrowser.open("http://localhost:5173")

        except Exception as e:
            logger.error(f"Failed to open browser: {e}")
            print(
                "\n💡 Manual access: Open your browser to http://localhost:5173 or http://localhost:3001"
            )

    def cleanup(self) -> None:
        """Clean up running processes."""
        logger.info("Shutting down FBA-Bench GUI...")

        for name, process in self.processes.items():
            if process and process.poll() is None:
                logger.info(f"Stopping {name}...")
                try:
                    process.terminate()
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                except Exception as e:
                    logger.error(f"Error stopping {name}: {e}")

        self.running = False
        logger.info("✓ FBA-Bench GUI shutdown complete")

    def run(self) -> None:
        """Main launcher entry point."""

        # Set up signal handlers for graceful shutdown
        def signal_handler(signum, frame):
            self.cleanup()
            sys.exit(0)

        signal.signal(signal.SIGINT, signal_handler)
        signal.signal(signal.SIGTERM, signal_handler)

        try:
            print("🚀 FBA-Bench Professional GUI Launcher")
            print("=" * 50)

            # Check requirements
            print("⏳ Checking system requirements...")
            requirements = self.check_requirements()

            missing_reqs = [name for name, available in requirements.items() if not available]
            if missing_reqs:
                print(f"❌ Missing requirements: {', '.join(missing_reqs)}")
                print("\nPlease install:")
                for req in missing_reqs:
                    if req == "poetry":
                        print("  - Poetry: https://python-poetry.org/docs/#installation")
                    elif req == "node":
                        print("  - Node.js: https://nodejs.org/")
                    elif req == "npm":
                        print("  - npm (comes with Node.js)")
                    elif req == "python":
                        print("  - Python 3.9+: https://python.org/downloads/")
                return

            print("✅ All requirements satisfied")

            # Check .env configuration
            print("⏳ Checking configuration...")
            env_status = self.check_env_configuration()

            if not env_status["exists"] or not env_status["valid"]:
                print("⚙️  Setting up configuration...")
                if not self.create_default_env():
                    print("❌ Failed to create configuration file")
                    return
                print("✅ Configuration created")
            else:
                print("✅ Configuration valid")

            # Start backend
            print("⏳ Starting backend services...")
            if not self.start_backend():
                print("❌ Failed to start backend")
                return

            # Start frontend
            print("⏳ Starting frontend interface...")
            if not self.start_frontend():
                print("❌ Failed to start frontend")
                self.cleanup()
                return

            # Open browser
            print("🌐 Opening web interface...")
            threading.Timer(2.0, self.open_browser).start()
            print("\n" + "=" * 50)
            print("🎉 FBA-Bench GUI is ready!")
            print("📊 Dashboard: http://localhost:5173 (or check terminal for exact port)")
            print("🔗 API Docs: http://localhost:8000/docs")
            print("📈 ClearML UI: http://localhost:8080 (admin@clear.ml / clearml123)")

            print("\nPress Ctrl+C to stop all services")
            print("=" * 50)

            # Keep running and monitor processes
            while self.running:
                # Check if processes are still running
                for name, process in self.processes.items():
                    if process and process.poll() is not None:
                        logger.error(f"{name} process stopped unexpectedly")
                        self.cleanup()
                        return

                time.sleep(2)

        except KeyboardInterrupt:
            self.cleanup()
        except Exception as e:
            logger.error(f"Launcher error: {e}")
            self.cleanup()


def main():
    """Entry point for GUI launcher."""
    launcher = FBABenchGUILauncher()
    launcher.run()


if __name__ == "__main__":
    main()
