environment = "${environment}"
domain_name = "${domain}"
public_app_base_url = "${public_app_base_url}"
api_image_tag = "${api_image_tag}"
frontend_image_tag = "${frontend_image_tag}"
jwt_secret = "CHANGE_ME_${tenant}"
stripe_secret_key = "sk_test_CHANGE_ME"