import logging
import os
import time
from pathlib import Path
from typing import Any, Dict, Optional

from dotenv import load_dotenv
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from fba_bench_api.api.dependencies import get_current_user

router = APIRouter(prefix="/setup", tags=["setup"])

logger = logging.getLogger(__name__)


class EnvCheckResponse(BaseModel):
    exists: bool
    valid: bool
    missing_keys: list[str]
    required_keys: list[str]
    environment: Optional[str] = None
    auth_enabled: Optional[bool] = None


class ConfigUpdateRequest(BaseModel):
    environment: str
    auth_enabled: bool
    cors_origins: str
    mongo_username: str
    mongo_password: str
    redis_password: str
    clearml_access_key: Optional[str] = None
    clearml_secret_key: Optional[str] = None


@router.get("/env-check", response_model=EnvCheckResponse)
async def check_env_configuration(
    current_user: Optional[Dict[str, Any]] = Depends(get_current_user),
):
    """
    Check the status of the .env configuration file.

    Returns whether the .env file exists, is valid, and which keys are missing.
    """
    env_path = Path(".env")

    if not env_path.exists():
        return EnvCheckResponse(
            exists=False,
            valid=False,
            missing_keys=[],
            required_keys=[
                "ENVIRONMENT",
                "AUTH_ENABLED",
                "FBA_CORS_ALLOW_ORIGINS",
                "MONGO_INITDB_ROOT_USERNAME",
                "MONGO_INITDB_ROOT_PASSWORD",
                "REDIS_PASSWORD",
                "FBA_BENCH_REDIS_URL",
            ],
        )

    # Load .env
    load_dotenv(env_path)

    # Required keys for validation
    required_keys = [
        "ENVIRONMENT",
        "AUTH_ENABLED",
        "FBA_CORS_ALLOW_ORIGINS",
        "MONGO_INITDB_ROOT_USERNAME",
        "MONGO_INITDB_ROOT_PASSWORD",
        "REDIS_PASSWORD",
        "FBA_BENCH_REDIS_URL",
    ]

    env_vars = {}
    missing_keys = []

    for key in required_keys:
        value = os.getenv(key)
        env_vars[key] = value
        if not value or value.strip() == "":
            missing_keys.append(key)

    # Bypass strict validation for development/testing (allow placeholders)
    environment = os.getenv("ENVIRONMENT", "development").strip().lower()
    if environment in ("development", "test"):
        valid = True
        missing_keys = []  # Ignore missing/empty for local testing
    else:
        valid = len(missing_keys) == 0

    response = EnvCheckResponse(
        exists=True,
        valid=valid,
        missing_keys=missing_keys,
        required_keys=required_keys,
        environment=os.getenv("ENVIRONMENT"),
        auth_enabled=os.getenv("AUTH_ENABLED", "false").lower() == "true",
    )

    logger.info(
        f"Env check: exists={response.exists}, valid={response.valid}, missing={len(response.missing_keys)} keys"
    )

    return response


@router.post("/update-config")
async def update_configuration(
    request: ConfigUpdateRequest, current_user: Optional[Dict[str, Any]] = Depends(get_current_user)
):
    """
    Update the .env configuration file with provided values.

    This endpoint writes the configuration to .env and reloads the environment.
    """
    try:
        env_path = Path(".env")

        # Prepare .env content
        env_content = f"""# FBA-Bench Configuration - Updated {time.strftime('%Y-%m-%d %H:%M:%S')}
# Auto-generated by FBA-Bench GUI Setup Wizard

# Environment Configuration
ENVIRONMENT={request.environment}
AUTH_ENABLED={str(request.auth_enabled).lower()}
FBA_CORS_ALLOW_ORIGINS={request.cors_origins}

# Database Configuration
MONGO_INITDB_ROOT_USERNAME={request.mongo_username}
MONGO_INITDB_ROOT_PASSWORD={request.mongo_password}
REDIS_PASSWORD={request.redis_password}
FBA_BENCH_REDIS_URL=redis://:{request.redis_password}@localhost:6379/0

# API Configuration
API_RATE_LIMIT=100/minute

# ClearML Configuration (Optional)
"""

        if request.clearml_access_key and request.clearml_secret_key:
            env_content += f"""CLEARML_API_ACCESS_KEY={request.clearml_access_key}
CLEARML_API_SECRET_KEY={request.clearml_secret_key}
"""

        env_content += """
# Note: For production deployments, review and customize these settings
# Do not commit this file with real secrets to version control
"""

        # Write to .env file
        with open(env_path, "w") as f:
            f.write(env_content)

        # Reload environment
        load_dotenv(env_path)

        logger.info(f"Configuration updated successfully for environment: {request.environment}")

        return {
            "success": True,
            "message": "Configuration saved successfully",
            "environment": request.environment,
        }

    except Exception as e:
        logger.error(f"Failed to update configuration: {e!s}")
        raise HTTPException(status_code=500, detail=f"Failed to save configuration: {e!s}")


@router.get("/health")
async def setup_health_check():
    """
    Health check endpoint for setup verification.

    Returns 200 if the basic setup is operational.
    """
    return {"status": "healthy", "service": "fba-bench-setup"}
